# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('http_headers_json', models.TextField()),
                ('cookies_json', models.TextField()),
                ('http_referer', models.TextField(blank=True)),
                ('remote_addr', models.TextField()),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webbug.Bug')),
            ],
        ),
    ]
