# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbug', '0002_auto_20170121_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='real_ip',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='remote_addr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='remote_port',
            field=models.TextField(blank=True),
        ),
    ]
