# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbug', '0003_auto_20170121_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='uuid',
            field=models.TextField(blank=True),
        ),
    ]
